### ISSUE TITLE
dir not uploaded

### ISSUE THREAD

**Issue by pulkitsinghal** [thousandsofthem/workers#2]
iron_worker cli tool can not explore dir contents over http protocol for turnkey workers so this lien in the worker file won't work until there is a fix: `dir 'bin'` ... right?

**Comment by thousandsofthem** [comment]
yes, http protocol do not support things like "dir", neither github (parsing the website is not what you want to do).
all the workers in current repo intended to be cloned/downloaded first and uploaded after - with modifications if needed

**Comment by pulkitsinghal** [comment]
In my opinion, if a convenient feature like turn-key deployment is provided then it should be polished all the way and there should be no need to change the worker file . Just my 2 cts.
